# Generated by Django 4.1.4 on 2023-03-11 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 11)),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(blank=True, default='05:06:45'),
        ),
    ]
