# Generated by Django 4.1.4 on 2023-03-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_post_date_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(blank=True, default='09:29:09'),
        ),
    ]
