# Generated by Django 4.1.4 on 2023-03-20 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0008_remove_post_is_saved_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profiles',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='social_media.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 20)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(blank=True, default='07:01:40'),
        ),
    ]
