# Generated by Django 4.1.4 on 2023-03-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0010_alter_post_date_alter_post_time_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
